package middleware

import (
	"log/slog"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5/middleware"
)

// LoggerMiddleware logs details of incoming HTTP requests and their corresponding responses.
// It leverages slog for structured logging and maps the request ID generated by Chi.
func LoggerMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		reqID := middleware.GetReqID(r.Context())

		// Wrap the ResponseWriter to capture the status code and bytes written
		ww := middleware.NewWrapResponseWriter(w, r.ProtoMajor)

		// Process the request
		next.ServeHTTP(ww, r)

		// Log completed request metrics
		slog.Info("HTTP request processed",
			slog.String("request_id", reqID),
			slog.String("method", r.Method),
			slog.String("path", r.URL.Path),
			slog.String("remote_addr", r.RemoteAddr),
			slog.Int("status", ww.Status()),
			slog.Int("bytes_written", ww.BytesWritten()),
			slog.Duration("latency", time.Since(start)),
		)
	})
}
